# Generated by Django 4.1.2 on 2023-05-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_director',
            field=models.BooleanField(default=True),
        ),
    ]
